### PR TITLE
Smartplay + Source select players for seren

### PR DESCRIPTION
**Pull request by henryjfry**
Two player files for the latest version of Seren which allow Source Select or Auto Play for both TV and MOVIES (currently only autoplay for movies is available).
Source Select for movies requires the mediatype to be omitted, otherwise it defaults to TV shows for some reason and then reports no playable sources.
Autoplay for TV and Movies works fine with either of the current player files, but i have named mine individually for easier identification.

### CODE REVIEW

**Comment by drinfernoo** [comment]
There is a difference between "Smart Play" (it actually isn't even called this anymore... though it was on early alpha builds of Seren. It's now called "Auto Playlist Creation".) and "Auto Play".

Ideally, we would have a handful of players:

* Source Select
* Auto Play
* Source Select w/ Smart Play
* Auto Play w/ Smart Play

The "Smart Play" players would really only apply to TV shows, since that feature doesn't do anything for movies.

Last time @rickdoesxmas uploaded similar players, they were broken, and only respected the settings that were set inside Seren, rather than what the URI in the player should've accomplished.

If you can figure out how to have those players work correctly for each type of content, and for them to override the settings *from* Seren, I'll merge this.

**Comment by henryjfry** [comment]
Ahh right, although im confused about what the difference between Auto Play and Auto Play with Smart Play would actually be (and similarly the two source select options).

There is another method: RunPlugin(plugin://plugin.video.%s?action=buildPlaylistWorkaround&actionArgs=%s)
Could that be the option  for movies that dont need a playlist?

What options is Seren ignoring? Because playing with source select and the mediatype removed for movies things play ok for me (there is an issue with cloud files but ive issued a separate pull request for that).
And for Autoplay for movies it seems to work ok too.

So if they work for TV/Episodes and they work for movies then surely they are working?
I got the fix implemented on my system but I thought other would want this too.

**Comment by drinfernoo** [comment]
I'll test these players and see if they're working as expected.

For TV Shows, there are truly four ways to play:

With Auto Play (but not Smart Play), Seren will play *one* episode, skipping Source Select. With Auto Play *and* Smart Play, it will continue in to the next episode, again skipping Source Select.

With Source Select (but no Smart Play), it should play one episode, and show the sources. With Source Select *and* Smart Play, it should continue to the next episode, showing sources each time.

In all of these scenarios, it would ideally ignore *any* of Seren's settings regarding Auto Play/Source Select and Smart Play, and *only* pay attention to the arguments passed with the player.

**Comment by henryjfry** [comment]
Ahh. Having had that explained I couldn't really say whether or not it's truly working then. I've got various next up things which are likely to try and kick in. Open meta, Seren, Realizer, the actual up next add-on which the skin uses too I think.
So while everything seems to be working for me I wasn't checking all those ins and outs.

I'll be interested to know if it is actually working like that now

**Comment by fugkco** [comment]
Any chance this will get merged at some point?

**Comment by drinfernoo** [comment]
@fugkco Given that OpenMeta is essentially abandoned at this point, I don't think anyone has actually tested the players regarding the points previously discussed.

**Comment by drinfernoo** [comment]
I have added "Source Select" players for TMDbHelper in the corresponding branch.

**Pull request closed without merging**
