### PR TITLE
fix ampersands in show titles

### PR DESCRIPTION
**Pull request by henryjfry**
fix ampersands in show titles

### CODE REVIEW

**Comment by drinfernoo** [comment]
The `escape()` function defined [here](https://github.com/a4k-openproject/plugin.video.openmeta/blob/master/resources/lib/text.py#L5) is used mostly throughout OpenMeta, as a way to avoid having to make these changes specifically in player files... Are there specific titles or add-ons that aren't working for you?

**Comment by henryjfry** [comment]
I had a specific problem with "Marvel's Cloak & Dagger" and it was causing a problem in every addon because the "link" variable would get truncated at the "&" in the showtitle.

**Comment by SerpentDrago** [comment]
Thanks fix at the addon level in works

**Comment by henryjfry** [comment]
I can post a pull request when I get home but the modification I had made to fix this myself are as follows:

play_tvshows.py:

#TOP OF FILE
#added to process dict "params[lang]" and change ' & ' to ' and '
import ast
######
######
######LINE 54
params[lang] = ast.literal_eval(repr(params[lang]).replace(' & ',' and '))
# xbmc.log('LOGHERE-----'+str(params[lang]) , level=2)
link = play_base.on_play_video(players, params, trakt_ids)

play_base.py:

########LINE 102
# link = text.apply_parameters(text.to_unicode(command['link']), parameters)
link = text.apply_parameters(text.to_unicode(command['link']), parameters).replace(' & ',' and ')
# xbmc.log(link, level=4)

**Comment by drinfernoo** [comment]
OpenMeta version 1.1.2 should fix these issues at the add-on level, so we don't need these player-specific fixes anymore.

**Pull request closed without merging**
